<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BanishBot
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace BanishBot\Api;

use \BanishBot\Configuration;
use \BanishBot\ApiClient;
use \BanishBot\ApiException;
use \BanishBot\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  BanishBot
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for getUserProfile
     *
     * Get the Users BanishBot Profile
     *
     */
    public function test_getUserProfile() {

    }
    
    /**
     * Test case for checkBanishment
     *
     * Check banishment of an item.
     *
     */
    public function test_checkBanishment() {

    }
    
    /**
     * Test case for banishNewObject
     *
     * Banish a new object
     *
     */
    public function test_banishNewObject() {

    }
    
    /**
     * Test case for deleteObject
     *
     * Deletes an object from BanishBot
     *
     */
    public function test_deleteObject() {

    }
    
}
